#!/usr/bin/env bash

# NOTICE: AI Generated by Gemini
# WARNING: We do not recommend running this script on pve-hosts where non-test-vms exist!

# Exit immediately if a pipeline fails
set -eo pipefail

# Define the target resource pool
POOL_NAME="ansible-molecule-vms"

echo "Starting cleanup of Proxmox pool: $POOL_NAME"

# Fetch pool members using pvesh and parse the JSON using python3 to extract qemu VM IDs
VM_IDS=$(pvesh get /pools/"$POOL_NAME" --output-format json 2>/dev/null | \
    python3 -c "import sys, json;
try:
    data = json.load(sys.stdin)
    members = data.get('members', [])
    for m in members:
        if m.get('type') == 'qemu' and 'vmid' in m:
            print(m['vmid'])
except Exception:
    pass")

# Check if we got any VM IDs
if [ -z "$VM_IDS" ]; then
    echo "No VMs found in pool '$POOL_NAME' or the pool does not exist."
    exit 0
fi

# Iterate over each found VMID and destroy it
for VMID in $VM_IDS; do
    echo "Processing VM ID: $VMID"

    # Try to stop the VM (ignore errors if it is already stopped)
    echo "  -> Stopping VM $VMID..."
    qm stop "$VMID" >/dev/null 2>&1 || true

    # Give Proxmox a moment to release cluster locks
    sleep 3

    # Destroy the VM, unreferenced disks, and purge it from the cluster configuration
    echo "  -> Destroying VM $VMID..."
    if qm destroy "$VMID" --purge 1 --destroy-unreferenced-disks 1; then
        echo "  -> Successfully destroyed VM $VMID."
    else
        echo "  -> WARNING: Failed to destroy VM $VMID."
    fi
done

echo "Cleanup of pool '$POOL_NAME' is complete."
