---

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Waiting for instance ssh connection
      ansible.builtin.wait_for_connection:

    - name: Set host name
      when: molecule_yml.driver.options.sethostname | d(true) | bool
      block:
        - name: Set instance hostname
          become: true
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}"

        - name: Gather facts
          ansible.builtin.setup:

        - name: Remove workaround loopback from /etc/hosts file
          become: true
          ansible.builtin.lineinfile:
            state: absent
            path: '/etc/hosts'
            regex: '^127\.0\.1\.1\s+\S+'

        - name: Add address and hostname to /etc/hosts file
          become: true
          ansible.builtin.lineinfile:
            state: present
            path: '/etc/hosts'
            line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"

        - name: Add static and dynamic IPs to /etc/hosts
          become: true
          ansible.builtin.lineinfile:
            state: present
            path: '/etc/hosts'
            line: >-
              {%- if item.value.startswith('PVE:') -%}
              {{ hostvars[item.value.split('PVE:')[1]]['ansible_host'] }} {{ item.key }}
              {%- else -%}
              {{ item.value }}
              {{ item.key }}
              {%- endif -%}
              {%- if item.value.startswith('PVE:') -%}
              {{ hostvars[item.value.split('PVE:')[1]]['ansible_host'] }} {{ item.key }}
              {%- else -%}
              {{ item.value }} {{ item.key }}
              {%- endif -%}
          loop: "{{ current_platform.etc_hosts | default({}) | dict2items }}"
          vars:
            current_platform: "{{ molecule_yml.platforms | selectattr('name', 'equalto', inventory_hostname) | first }}"
          when: current_platform.etc_hosts is defined
          tags: [skip_ansible_lint]  # jinja[spacing]
